// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Alignment =
	| "LawfulGood"
	| "NeutralGood"
	| "ChaoticGood"
	| "LawfulNeutral"
	| "TrueNeutral"
	| "ChaoticNeutral"
	| "LawfulEvil"
	| "NeutralEvil"
	| "ChaoticEvil";
