// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alignment } from "./Alignment";
import type { Sex } from "./Sex";
import type { Size } from "./Size";

export type BasicDescription = { race: string, sex: Sex, size: Size, age: number, height: string, weight: number, alignment: Alignment, };
