// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AbilityScore = { name: string, short_name: string, is_proficient: boolean, score: number, };
