// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AbilityScore = {
	name: string;
	shortName: string;
	isProficient: boolean;
	score: number;
	additionalMods: number;
	baseModifier: number;
	totalMod: number;
};
