// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbilityScore } from "./AbilityScore";
import type { BasicDescription } from "./BasicDescription";
import type { CombatStats } from "./CombatStats";
import type { Skill } from "./Skill";

export type CharacterDetails = {
	id: number;
	name: string;
	creator: string;
	basic_description: BasicDescription;
	combat_stats: CombatStats;
	languages: Array<string>;
	ability_scores: [
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore
	];
	skills: [
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill
	];
	kill_list: Array<string>;
	created_at: string;
	updated_at: string;
};
