// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CombatStats = {
	initiativeMods: number;
	speed: number;
	speedMods: number;
	maxHp: number;
	currentHp: number;
	tempHp: number;
	hitDiceRemaining: number;
};
