// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CombatStats = {
	initiative_mods: number;
	speed: number;
	speed_mods: number;
	max_hp: number;
	current_hp: number;
	temp_hp: number;
	hit_dice_remaining: number;
};
