// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbilityScore } from "./AbilityScore";
import type { BasicDescription } from "./BasicDescription";
import type { CombatStats } from "./CombatStats";
import type { Skill } from "./Skill";

export type FullCharacterData = {
	id: number;
	name: string;
	creator: string;
	basicDescription: BasicDescription;
	combatStats: CombatStats;
	languages: Array<string>;
	abilityScores: [
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore,
		AbilityScore
	];
	skills: [
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill,
		Skill
	];
	killList: Array<string>;
	createdAt: string;
	updatedAt: string;
};
