// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

export type Skill = { name: string, is_proficient: boolean, has_expertise: boolean, ability_name: Ability, };
